### ISSUE TITLE
Preparar slides #1 para la presentación 22-02

### ISSUE THREAD

**Issue by lauralozanoalvarez** [lpamelalozano/lim008-ux-financial-app#14]
Deberíamos tener:
[ ] User Persona
[ ] Customer Journey Map
[ ] Benchmark
[ ] Sintesis de los insights principales cliente - usuario

Con fe 👩‍💻 😀

**Comment by krpando** [comment]
Done!
Cosas que mejorar para la siguiente presentación:
- Verificar tamaño y calidad de las imágenes presentadas
- Dejar tiempo prudencial para mostrar el prototipo en funcionamiento
- Sustentar conclusiones: Elección de User Persona, Iteración de diseño, etc.
