### ISSUE TITLE
Definir herramientas y entregables

### ISSUE THREAD

**Issue by lauralozanoalvarez** [lpamelalozano/lim008-ux-financial-app#2]
- Sustentar la elección de cada herramienta 
- Validar con coach 
- Definir los entregables

**Comment by krpando** [comment]
Se realiza elección de herramientas y presupuesto del proyecto. Queda pendiente validar con couches.

**Comment by lauralozanoalvarez** [comment]
Karlita, según lo acordado, adjunto la elección de herramientas.
Con respecto a los entregables:
- User Persona
- User Flow ideal 
- Prototipo de alta fidelidad navegable y diseño en Figma 
- Zeplin 
- Benchmark
- Reporte / Informe:
 * Análisis, conclusiones y recomendaciones para la empresa 

https://docs.google.com/spreadsheets/d/1Pim7KAL9oLvIb51dg95LUgXA0e8fgrC7NtjlzhIp4rk/edit?usp=sharing
