### ISSUE TITLE
Elaboración de Screener Survey

### ISSUE THREAD

**Issue by krpando** [lpamelalozano/lim008-ux-financial-app#3]
- Construcción y elección de preguntas.
- Elaboración de formulario.
- Envío de formulario a contactos para recojo de información.

**Comment by lauralozanoalvarez** [comment]
Ya está, falta que lo llenen nomás 😭 
Link: https://docs.google.com/forms/d/1F4TvW9LN5GiK2kKuFuH2Avn0sYBj45BesN7bYrxXQMA/edit?usp=drive_web
