### ISSUE TITLE
Entrevistas a usuarixs

### ISSUE THREAD

**Issue by krpando** [lpamelalozano/lim008-ux-financial-app#5]
- [x] Elaborar Guía de entrevista a usuarixs.
- [x] Agendar entrevistas a 5 usuarixs como mínimo.
- [x] Aplicar entrevistas
- [x] Subir documentación a Google Drive
- [x] Actualizar Readme

**Comment by lauralozanoalvarez** [comment]
Ya hay 5 entrevistas como mínimo, hoy por si acaso culmina Karlita con dos más 
Están en drive: https://drive.google.com/drive/u/0/folders/1elLIcZ1imRn5NHgRBdktoKVN1rLCJRbk
💃
